= Clean Agile

* TDD
* Refactoring
* Simple Design

* Acceptance Tests
* Continuous Integration


* ++ Exploratory Testing


* Cubrirnos los unos a los otros
    ** Compartir conocimiento


. Agile Practices
    .. Pair Programming
    .. Whole Team
    .. Collective Ownership

* Continuous Aggressive Learning

== Planning

* Business-facing practices
    * Planning
    * Small Releases
    * Acceptance Tests
    * Whole Team



. _trivariate estimation_:

    .. best-case
    .. nominal-case
    .. worst-case


NOTE: PERT `Program Evaluation and Review Techniques`


* *_story points_:* 

=== Stories And Points

A *_user story_* is an abbreviated description of a feature of the system, told from the point of view of a user.

Typically, we write the story on an index card

What makes a story manageable, schedulable, and estimable is the temporary lack of detail.

Stories must start out cheap because a lot of them are going  to be modified, split, merged, or even discarded.

Now we have a batch of story cards created in Iteration Zero. Others will be created later as new features and new ideas are encountered. In fact, the process of story creation never ends

Points: They are a unit of estimated effort, not real time.

NOTE: Law of Large Numbers


=== Planning Iteration One

* *_Iteration Planning Meeting_* *(IPM)* 

    ** Should be scheduled to be one-twentieth the duration of the iteration, The IPM for a two-week iteration should require a half a day.
    
    ** The stakeholders will have previously read the estimated stories and sorted them in the order of business value. Some teams actually choose number for that business value.

    ** The job of the stakeholders at the IPM is to choose the stories that will be implemented by the programmers and testers during the iterarion. To do this they need to know how many story points the programmers think they can complete. _This number is called the_ *-velocity-*

=== Return on Investment

.four-quadrant game
[cols=">h,,",width="70%" ]
|===
||High Cost |Low Cost

|High Value|*Do Later*
|*Do Now*

|Low Value|Never Do
|Do Much Later
|===

NOTE: The stories that are valuable but cheap will be done right away.

This is a _return on investment_ (ROI) calculation

=== The Midpoint Check

* There is some procedure for turning stories into working code. Think of it as moving story cards from the _planned pile_ to the _done pile_.

* *_Iterations do not fail_* the purpose of an iteration is to generate data for managers.

=== Yesterday's Weather

* The best predictor of the progress of an iteration is the previous iteration. This is called *_yesterday's weather_*.

=== The End of the Project

The project is not over when all the stories are implemented. The project is over when there are no more stories in the deck worth implementing.

=== Stories

*User stories are simple statements that we use as reminders of features*. We try not to record too much detail when we write the story because we know that those details will likely change.

Stories follow a simple set of guidelines that we remember with the acronym *_INVEST_*.

* *_I: Independent_*.
* *_N: Negotiable_*.
* *_V: Valuable_*.

    ** Refactoring is _never_ a story. Architecture is never a story. Code cleanup is never a story. *_A story is always something that the business values_*

* *_E: Estimable_*.
* *_S: Small_*.
* *_T: Testable_*.

=== Story Estimation

* Wideband Delphi
* Flying Fingers
* Shirt Sizes: Small, Medium, and Large
* Planning Poker

=== Splitting, Merging, and Spiking

=== Managing the Iteration

* The goal of each iteration is to produce data by getting stories done. The team should focus on stories rather than tasks within stories.

* It is far better to get 80% of stories done than it is get each story 80% done. _Focus on driving the stories to completion_.

* As soon as the planning meeting ends, the programmers should choose the stories for which they individually be responsible.

* Managers and leads will be tempted to assign stories to programmers. *_This should be avoided_*

=== QA and Acceptance Tests

* The tests for stories  that are scheduled for early completion should be done early.

* If not all the _acceptance tests_ are ready by the midpoint, then some of the developers should stop working on stories and start working on acceptance tests.

* This will likely mean that not all the stories will be completed in this iteration, *_but a story cannot be completed without the acceptance tests anyway_*.

* Just be sure that the programmers working on a story are not also writing the acceptance tests for that story.

* If a QA continues to miss the midpoint deadline, one iteration after another, then the ratio of QA engineers to developers is likely wrong.

* The definition of "done" is this: *_acceptance tests pass_*.

=== The Demo

* The iteration ends with a brief demostration of the new stories to the stakeholders.
    ** The demo should include showing that all the acceptance tests run.
    ** Including all _previous_ acceptance tests and all _unit tests_.
    ** It should also show off the newly added features. It is best if the stakeholders themselves operate the system.

=== Velocity

* The last act of the iteration is to update the velocity and burn-down charts.

    ** Only the points for stories that have passed their acceptance tests are recorded on these charts.
    ** After several iterations. both of these charts will begin to show a slope.
    ** The burn-down slope predicts the date for the next major milestone.
    ** *_The velocity slope tells us how well the team is being managed_*.

==== Rising Velocity
    * Velocity is a *_measurement_* not an objective.

==== Falling Velocity
    * If the velocity chart shows a consistent negative slope, then the most likely cause is the quality of the code.

=== Small Releases

* The practice of *_Small Releases_* suggests that a development team should release their software as often as posible.

* *_Continuous Delivery_*: the practice of releasing the code to production after every change.

=== Source Code Control

* _pessimistic lock_

* Punched Cards
* Tapes
* Disks and SCCS
* Subversion
* Git and Tests

==== Historical Inertia

* Unfortunately, it is difficult for organizations to shake off the behavior of the past. The cycle time of days, weeks, and months is deeply ingrained in the culture of many teams and has spread to QA, to management, and to the expectations of the stakeholders.

==== Small Releases

* Agile attempts to break that historical inertia by driving the team to shorter and shorter release cycles.

* The term *_"release"_* means that the software is technically ready to be deployed. The decision to deploy becomes solely a business decision.

=== Acceptance Tests

* This practice is one of the least understood, least used and most confused of all the Agile practices. This is strange because the underlying idea is remarkably simple: *_Requirements should be specified by the business_*.

* *_specify_* (business) vs *_precisely_* (programmers): Something in the middle of these two extremes is necessary.

* So whats is a specification? A specification is, by its very nature, a _test_.

** *_When the user enters a valid username and password, and then clicks "login", the system will present the "Welcome" page._*

* It should also be obvious that this test could automated.

* Who writes these automated tests? QA

=== Tools and Methodologies

==== Behavior-Driven Development

* The goal of `Behavior-Driven Development (TDD)` was to remove the techie jargon from the tests and make the tests appear more like specifications

* Using three special adverbs:

    ** Given
    ** When
    ** Then

=== The Practice

* *_Definition of Done_*: The developers integrate those tests into the continuous build. Those tests become the Definition of Done for the stories in the iteration.

* A story is not specified until its acceptance test is written. A story is not complete until its acceptance test passes.

==== Business Analysts and QA

* Acceptance tests are a collaborative effort between business analysts, QA, and the developers.

    ** *_Business Analysts_*: Specify the happy paths. That's because they have enough to do in their role of communicating between the programmers and the stakeholders.

    ** *_QA_*: QA's role is write the unhappy paths. QA folks are hired for their ability to figure out how to break the system.

    ** *_Developers_*: Work with QA and business analysts to ensure that the tests make sense from a technical point of view.

=== Whole Team

* This practice was initially calle *_On-Site Customer_*. The idea was that the shorter the distance between the users and the programmers, the better the communication, and the faster and more accurate the development.

* The *_customer_* was a metaphor for someone, or some group, who understood the needs of the users, and who was co-located with the development team.

* In Scrum, the customer is called the Product Owner. This is the person who chooses stories, sets priorities, and provides immediate feedback.

* A development team is composed of many roles including managers, testers, technical writers.

* *The goal of the practice is to minimize the physical distance between these roles*

== TEAM PRACTICES

_Team Practices of Agile_ these practices govern the relationship of the team members with one another and with the product they are creating.

The Practices we will discuss are:

* Metaphor
* Sustainable Pace
* Collective Ownership
* Continuous Integration
* Then we'll talk briefly about so-called _Standup Meetings_

=== _Metaphor_

* A metaphor can provide a vocabulary that allows the team to communicate efficiently.

==== Domain-Driven Design

In his groundbraking book _Domain-Driven Design_, Eric Evans solved the metaphor problem, in that book, he coined the term *_Ubiquitous Language_*, whoich is the name that should have been given to the *_Metaphor_* practice.

=== _Sustainable Pace_

==== Overtime

* I realized that my worst technical mistakes were made during those periods of frenetic late-night energy

==== Marathon

* I learned that a software project is a marathon, not a sprint, nor a sequence of sprints

==== Dedication

==== Sleep

=== _Collective Ownership_

* *_Collective Ownership_* does not mean that you cannot specialize. As systems grow in complexity, specialization  becomes an absolute necessity.

* There are systems tha simply cannot be understood in both entirety and detail.

* When a team practices *_Collective Ownership_*, knowledge becomes distributed across the team. Each team member gains a better understanding of the boundaries between modules and of the overall way that the system works. _This drastically improves the ability of the team to communicate and make decisions_.

== Chapter 5 : TECHNICAL PRACTICES

* TDD
* Refactoring
* Simple Design
* Pair Programming

=== TEST-DRIVEN DEVELOPMENT

==== The Three Rules of TDD

TDD can be described with three simple rules.

* Do not write any production code until you have first written a test that fails due to the lack of that code.

* Do not write more of a test than is sufficient to fail and failing to compile counts as a failure.

* Do not write more production code than is sufficient to pass the currently failing test.

==== Debugging

==== Documentation

==== Design

* *_When you write the test first_*, something very different happens. You *_cannot_* write a function that is hard to test.

    ** Since you are writing the test first, you will naturally design the function you are testing to be easy to test. *_How do you keep functions easy to test?_* You decouple them. Indeed, testability is just a synonym for decoupling.

* It is for this reason tha *TDD* is often called a *design technique*. The Three Rules forces you into a much higher degree of decoupling.

=== REFACTORING

* *_Refactoring_* is the practice of *_improving_* the structure of the code without altering the behavior, as defined by the tests.

    ** We make changes to the names, the classes, the functions, and the expressions without breaking any of the tests.
    ** We improve the structure of the system, without affecting the behavior.
    ** This practice couples strongly with TDD.

* The kinds of changes made during refactoring range from trivial cosmetics to deep restructurings.

    ** The changes might be simple name changes or complex reshufflings of switch statements to polymorphics dispatches.
    ** Large functions will be split into smaller, better-named, functions.
    ** Arguments lists will be changed into objects.
    ** Classes with many methods will be split into many smallers classes.
    ** Functions will be moved from one class to another.
    ** *Dependencies will be inverted, and modules will be moved across architectural boundaries*.

==== Red/Green/Refactor

. First, we create a test that fails.
. Then we make the test pass.
. Then we clean up the code.
. Return to step 1.

---

* *_Refactoring is a continuous process_*, and not one that is performed on a scheduled basis.

* The word *_Refactoring_* should never appear on a schedule. Refactoring is not the kind of activity that appears on a plan.

* Refactoring is simply part of our minute-by-minute, hour-by-hour approach to writing software.

==== Bigger Refactorings



=== SIMPLE DESIGN

The practice of *_Simple Design_* is one of the goals of Refactoring. Simple Design *_is the practice of writing only the code that is required_* with a structure that keeps it simplest, smallest, and most expensive.

Kent Beck's rules of Simple Design are as follows:

. Pass all the tests.
. Reveal the intent.
. Remove duplication.
. Decrease elements.

[NOTE]
.Design Patterns: Removing Duplication
====
* Template method
* Strategy
* Decorator
* Visitor
====

The goal of Simple Design is to keep the *_design weight_* of the code as small as practicable.

==== Design Weight

=== PAIR PROGRAMMING

